### ISSUE TITLE
Tested issues on some screen sizes/scalings.

### ISSUE THREAD

**Issue by awgv** [PrimeJunta/numenera#2]
Hello,

I've encountered a problem on 1920x1080 tablet screen (150% page scaling), and checked it on PC (also 1920x1080, but with 100% scaling) — this is not a browser-specific issue.

The problem is the fixed navigation bar on play view: if the screen height is not enough for whatever reason may be, the bar overlaps and cuts off character information.

Possible, really quick fix is to "overflow:scroll;" the whole page, and add new style for the latest .cr-content class on a page, which is "margin-bottom: 69px;", to compensate the height of the navigation bar. This must be done on all tabs of the play view + help tab; the first tab is already scrollable — also must be changed, if such fix is implemented.

Similar issue exists on the main page, where fixed legal information overlaps "Remembered Heroes" button making it unclickable/untouchable. You can model the problem by resizing your browser window.

We played the game with this character sheet a few days ago and had a blast, thank you!

Regards,
   Andrew.

**Comment by PrimeJunta** [comment]
Thanks for the comment and I'm glad you've enjoyed it. I'll see what I can do about this issue when I have some time. I hope to make things scale better to smaller screen sizes at some point; this quick fix should be easy to apply.
